### ISSUE TITLE
No module named libmproxy

### ISSUE THREAD

**Issue by theoneandonly-vector** [JonDoNym/peinjector#9]
No module named libmproxy

probably something changed in the mitmproxy software..

interceptor.err:
Traceback (most recent call last):
  File "./peinjector_interceptor.py", line 11, in <module>
    from libmproxy import controller, proxy
ImportError: No module named libmproxy
Traceback (most recent call last):
  File "./peinjector_interceptor.py", line 11, in <module>
    from libmproxy import controller, proxy
ImportError: No module named libmproxy

**Comment by theoneandonly-vector** [comment]
the module libmproxy is now officially mitmproxy. so I changed that in "peinjector_interceptor.py"
but now I get another error:
AttributeError: 'module' object has no attribute 'IntEnum'

full-log:
Traceback (most recent call last):
  File "./peinjector_interceptor.py", line 11, in <module>
    from mitmproxy import controller, proxy
  File "/usr/lib/python2.7/dist-packages/mitmproxy/proxy/**init**.py", line 3, in <module>
    from .config import ProxyConfig
  File "/usr/lib/python2.7/dist-packages/mitmproxy/proxy/config.py", line 16, in <module>
    from netlib.http import authentication
  File "/usr/lib/python2.7/dist-packages/netlib/http/**init**.py", line 2, in <module>
    from netlib.http.request import Request
  File "/usr/lib/python2.7/dist-packages/netlib/http/request.py", line 13, in <module>
    from netlib.http import message
  File "/usr/lib/python2.7/dist-packages/netlib/http/message.py", line 8, in <module>
    from netlib import encoding, strutils, basetypes
  File "/usr/lib/python2.7/dist-packages/netlib/encoding.py", line 13, in <module>
    import brotli
  File "/usr/lib/python2.7/dist-packages/brotli/**init**.py", line 3, in <module>
    from .brotli import (
  File "/usr/lib/python2.7/dist-packages/brotli/brotli.py", line 25, in <module>
    class BrotliEncoderMode(enum.IntEnum):
AttributeError: 'module' object has no attribute 'IntEnum'

**Comment by JonDoNym** [comment]
Which os are you using, btw. what's your mitmproxy version?

We know that there are problems with mitmproxy/libmproxy, they are constantly breaking stuff and compatibility. Try to stay at an older, working version and don't update mitmproxy/libmprox if possible. You can use an virtual environment for this, if you need an up-to-date version of mitmproxy.

It is on our agenda to find a replacement for mitmproxy/libmproxy, but we are very busy at the moment.
If you know a good mitm library which allows seamless modification (no complete buffering), let us know.
